spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/taskforge
    username: taskforge
    password: taskforge
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2

logging:
  level:
    org.hibernate.SQL: debug
