spring:
  application:
    name: taskforge-api
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true

app:
  jwt:
    access-token-ttl: 15m
  refresh-token:
    ttl: 30d
